<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Wixpack.Core\Wixpack.Core.csproj" />
    <ProjectReference Include="..\Wixpack.Telegram\Wixpack.Telegram.csproj" />
    <ProjectReference Include="..\Wixpack.Floket\Wixpack.Floket.csproj" />
    <ProjectReference Include="..\Wixpack.Games\Wixpack.Games.csproj" />
    <ProjectReference Include="..\Wixpack.Downloader\Wixpack.Downloader.csproj" />
    <ProjectReference Include="..\Wixpack.DevTools\Wixpack.DevTools.csproj" />
    <ProjectReference Include="..\Wixpack.Experimental\Wixpack.Experimental.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <ItemGroup>
    <None Update="config\settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>

